---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsdeployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: kirti2024/assessmentpurpose:15
        ports:
        - containerPort: 8080
        - containerPort: 50000
        
          
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: jenkins
