apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-helm.serviceAccountName" . }}
  labels:
    {{- include "nginx-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
root@ip-172-31-42-164:/home/ubuntu/nginx-helm/templates# cd ..
root@ip-172-31-42-164:/home/ubuntu/nginx-helm# ls
Chart.yaml  charts  templates  values.yaml

replicaCount: 1

image:
  repository: mbranchpurpose
  
  pullPolicy: IfNotPresent
  
  tag: "kirti2024/mbranchpurpose:15"
    

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "helm-service-account"
podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


volumes: []

volumeMounts: []


nodeSelector: {}

tolerations: []

affinity: {}
